# Generated by Django 4.1.6 on 2023-02-11 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_card_date_created_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='text',
            new_name='html',
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 14, 21, 45, 294041)),
        ),
    ]
