# Generated by Django 4.1.5 on 2023-02-14 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_text_card_html_alter_card_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='brandLogo',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='featuredContentMedia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='headshotImage',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 23, 15, 41, 757556)),
        ),
    ]
