# Generated by Django 4.1.5 on 2023-02-19 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_card_brandlogo_card_featuredcontentmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='business_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='business_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='business_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='job_title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='prefix',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 11, 58, 6, 181580)),
        ),
    ]
