# Generated by Django 4.1.6 on 2023-02-19 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card_guest_user_alter_card_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 14, 24, 16, 856473)),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
