# Generated by Django 4.1.6 on 2023-02-19 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_card_guest_user_alter_card_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='media_keys',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 21, 14, 39, 827079)),
        ),
    ]
