# Generated by Django 4.1.7 on 2023-02-25 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_card_media_keys_alter_card_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 8, 21, 16, 569836)),
        ),
    ]
